<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>11.0</LangVersion>
    <AssemblyName>RcSourceVerify</AssemblyName>
    <RootNamespace>RcSourceVerify</RootNamespace>
    <Nullable>disable</Nullable>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.Data.SQLite.Core" Version="1.0.119" />
    <ProjectReference Include="..\..\..\LedgerModel\LedgerModel.csproj" />
  </ItemGroup>
</Project>
